---
excludes:
  paths:
    - pattern: "examples/**"
      reason: "EXAMPLE_OF"
  scopes:
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
resolutions:
  rule_violations:
    - message: ".*PyPI::httpcore:1\\.0\\.5.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause New or Revised License: https://github.com/encode/httpcore/blob/1.0.5/LICENSE.md"
    - message: ".*PyPI::httpx:0\\.27\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause New or Revised License: https://github.com/encode/httpx/blob/0.27.2/LICENSE.md"
    - message: ".*PyPI::numpy:1\\.26\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause New or Revised License: https://github.com/numpy/numpy/blob/v1.26.4/LICENSE.txt"
    - message: ".*PyPI::tiktoken:0\\.9\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/openai/tiktoken/blob/0.9.0/LICENSE"
    - message: ".*PyPI::aiohappyeyeballs:2\\.4\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "PSF-2.0: https://github.com/aio-libs/aiohappyeyeballs/blob/v2.4.0/LICENSE"