[tox]
env_list =
    lint
    format
    py{310,311,312,313}-lc{0_1_1,0_1_25,0_2_0,0_2_14,0_3_0,0_3_18}-test_monkey_patch
    py{310,311,312,313}-openai{1_48_0,1_58_1}-test_openai
skipsdist = True
requires = tox>=4.0

[testenv]
deps =
    .[lint,test]
    lc0_1_1: langchain_openai==0.1.1
    lc0_1_25: langchain_openai==0.1.25
    lc0_2_0: langchain_openai==0.2.0
    lc0_2_14: langchain_openai==0.2.14
    lc0_3_0: langchain_openai==0.3.0
    lc0_3_18: langchain_openai==0.3.18
    openai1_48_0: openai==1.48.0
    openai1_58_1: openai==1.58.1
commands =
    test_monkey_patch: pytest tests/test_langchain_monkey_patch.py tests/test_langchain_noop.py
    test_openai: pytest tests/test_openai.py

[testenv:lint]
description = run code style checker and a type checker
commands =
    pyright .
    flake8 .
    autoflake . --check
    isort . --check
    black . --check

[testenv:format]
description = run code style auto-formatting
commands =
    autoflake .
    isort .
    black .
