name: "Validate PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-check:
    if: false  # disable the job
    uses: epam/ai-dial-ci/.github/workflows/pr-title-check.yml@2.2.0
    secrets:
      ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
